package kr.pe.hws.stock.exchange.rate

import java.math.BigDecimal

data class ExchangeRate(
    val id: Long,
    val code: String,
    val currencyCode: String,
    val currencyName: String,
    val country: String,
    val name: String,
    val date: String,
    val time: String,
    val recurrenceCount: Int,
    val basePrice: BigDecimal,
    val openingPrice: BigDecimal,
    val highPrice: BigDecimal,
    val lowPrice: BigDecimal,
    val change: String,
    val changePrice: BigDecimal,
    val cashBuyingPrice: BigDecimal,
    val cashSellingPrice: BigDecimal,
    val ttBuyingPrice: BigDecimal,
    val ttSellingPrice: BigDecimal,
    val tcBuyingPrice: BigDecimal,
    val fcSellingPrice: BigDecimal,
    val exchangeCommission: BigDecimal,
    val usDollarRate: BigDecimal,
    val high52wPrice: BigDecimal,
    val high52wDate: String,
    val low52wPrice: BigDecimal,
    val low52wDate: String,
    val currencyUnit: Int,
    val provider: String,
    val timestamp: Long,
    val createdAt: String,
    val modifiedAt: String,
    val signedChangePrice: BigDecimal,
    val signedChangeRate: BigDecimal,
    val changeRate: BigDecimal,
)
