package kr.pe.hws.stock.rdb.entity

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import kr.pe.hws.stock.exchange.rate.ExchangeRate
import java.math.BigDecimal

@Entity
@Table(name = "exchange_rate")
class ExchangeRateEntity(
    @Id
    val id: Long,
    val code: String,
    val currencyCode: String,
    val currencyName: String,
    val country: String,
    val name: String,
    val date: String,
    val time: String,
    val recurrenceCount: Int,
    val basePrice: BigDecimal,
    val openingPrice: BigDecimal,
    val highPrice: BigDecimal,
    val lowPrice: BigDecimal,
    @Column(name = "\"change\"")
    val change: String,
    val changePrice: BigDecimal,
    val cashBuyingPrice: BigDecimal,
    val cashSellingPrice: BigDecimal,
    val ttBuyingPrice: BigDecimal,
    val ttSellingPrice: BigDecimal,
    val tcBuyingPrice: BigDecimal?,
    val fcSellingPrice: BigDecimal?,
    val exchangeCommission: BigDecimal,
    val usDollarRate: BigDecimal,
    val high52wPrice: BigDecimal,
    val high52wDate: String,
    val low52wPrice: BigDecimal,
    val low52wDate: String,
    val currencyUnit: Int,
    val provider: String,
    val timestamp: Long,
    val createdAt: String,
    val modifiedAt: String,
    val signedChangePrice: BigDecimal,
    val signedChangeRate: BigDecimal,
    val changeRate: BigDecimal,
) {
    constructor(exchangeRate: ExchangeRate) : this(
        id = exchangeRate.id,
        code = exchangeRate.code,
        currencyCode = exchangeRate.currencyCode,
        currencyName = exchangeRate.currencyName,
        country = exchangeRate.country,
        name = exchangeRate.name,
        date = exchangeRate.date,
        time = exchangeRate.time,
        recurrenceCount = exchangeRate.recurrenceCount,
        basePrice = exchangeRate.basePrice,
        openingPrice = exchangeRate.openingPrice,
        highPrice = exchangeRate.highPrice,
        lowPrice = exchangeRate.lowPrice,
        change = exchangeRate.change,
        changePrice = exchangeRate.changePrice,
        cashBuyingPrice = exchangeRate.cashBuyingPrice,
        cashSellingPrice = exchangeRate.cashSellingPrice,
        ttBuyingPrice = exchangeRate.ttBuyingPrice,
        ttSellingPrice = exchangeRate.ttSellingPrice,
        tcBuyingPrice = exchangeRate.tcBuyingPrice,
        fcSellingPrice = exchangeRate.fcSellingPrice,
        exchangeCommission = exchangeRate.exchangeCommission,
        usDollarRate = exchangeRate.usDollarRate,
        high52wPrice = exchangeRate.high52wPrice,
        high52wDate = exchangeRate.high52wDate,
        low52wPrice = exchangeRate.low52wPrice,
        low52wDate = exchangeRate.low52wDate,
        currencyUnit = exchangeRate.currencyUnit,
        provider = exchangeRate.provider,
        timestamp = exchangeRate.timestamp,
        createdAt = exchangeRate.createdAt,
        modifiedAt = exchangeRate.modifiedAt,
        signedChangePrice = exchangeRate.signedChangePrice,
        signedChangeRate = exchangeRate.signedChangeRate,
        changeRate = exchangeRate.changeRate,


    )
}

fun ExchangeRateEntity.toDomain() = ExchangeRate(
    id = id,
    code = code,
    currencyCode = currencyCode,
    currencyName = currencyName,
    country = country,
    name = name,
    date = date,
    time = time,
    recurrenceCount = recurrenceCount,
    basePrice = basePrice,
    openingPrice = openingPrice,
    highPrice = highPrice,
    lowPrice = lowPrice,
    change = change,
    changePrice = changePrice,
    cashBuyingPrice = cashBuyingPrice,
    cashSellingPrice = cashSellingPrice,
    ttBuyingPrice = ttBuyingPrice,
    ttSellingPrice = ttSellingPrice,
    tcBuyingPrice = tcBuyingPrice,
    fcSellingPrice = fcSellingPrice,
    exchangeCommission = exchangeCommission,
    usDollarRate = usDollarRate,
    high52wPrice = high52wPrice,
    high52wDate = high52wDate,
    low52wPrice = low52wPrice,
    low52wDate = low52wDate,
    currencyUnit = currencyUnit,
    provider = provider,
    timestamp = timestamp,
    createdAt = createdAt,
    modifiedAt = modifiedAt,
    signedChangePrice = signedChangePrice,
    signedChangeRate = signedChangeRate,
    changeRate = changeRate,
)
